// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGNP22PaWEQ9HljKmvuAaQa-LKPFze21Q',
    appId: '1:319575415835:web:ed70b2701f722630c32cbe',
    messagingSenderId: '319575415835',
    projectId: 'fitness-app-18217',
    authDomain: 'fitness-app-18217.firebaseapp.com',
    storageBucket: 'fitness-app-18217.firebasestorage.app',
    measurementId: 'G-57MZSB22HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMY-rTt_VdY9sdteX0AbWENGzyN0x48Rg',
    appId: '1:319575415835:android:32221a8f183c0360c32cbe',
    messagingSenderId: '319575415835',
    projectId: 'fitness-app-18217',
    storageBucket: 'fitness-app-18217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzO4YxpDkUtW9i5z5ZiMuxr-A5uaWcSeA',
    appId: '1:319575415835:ios:90d4137e5e968d35c32cbe',
    messagingSenderId: '319575415835',
    projectId: 'fitness-app-18217',
    storageBucket: 'fitness-app-18217.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzO4YxpDkUtW9i5z5ZiMuxr-A5uaWcSeA',
    appId: '1:319575415835:ios:90d4137e5e968d35c32cbe',
    messagingSenderId: '319575415835',
    projectId: 'fitness-app-18217',
    storageBucket: 'fitness-app-18217.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGNP22PaWEQ9HljKmvuAaQa-LKPFze21Q',
    appId: '1:319575415835:web:d0b46b6cfd604722c32cbe',
    messagingSenderId: '319575415835',
    projectId: 'fitness-app-18217',
    authDomain: 'fitness-app-18217.firebaseapp.com',
    storageBucket: 'fitness-app-18217.firebasestorage.app',
    measurementId: 'G-DH8KSFGBKY',
  );
}
